name: "Nix CI"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Cancel in-progress runs when a new push is made to the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Flake Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Nix Flake
        run: nix flake check

  build-nixos:
    name: Build NixOS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [helm, vessel-01, vessel-02]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build NixOS Configuration
        run: nix build .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel --dry-run

  build-home-manager:
    name: Build Home Manager
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        host: [anchor-01]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Home Manager Configuration
        run: nix build .#homeConfigurations.${{ matrix.host }}.activationPackage --dry-run
